module.exports = {
  apps: [
    {
      name: 'quantcase-backend',
      script: 'server.js',
      env: { PORT: 8000 },
      autorestart: true,
      max_restarts: 10,
      min_uptime: '30s',
      restart_delay: 5000,
      max_memory_restart: '1G',
      out_file: 'logs/backend-out.log',
      error_file: 'logs/backend-error.log',
      time: true,
    },
    {
      name: 'quantcase-worker',
      script: 'worker.js',
      node_args: '--max-old-space-size=8192',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '30s',
      restart_delay: 5000,
      out_file: 'logs/worker-out.log',
      error_file: 'logs/worker-error.log',
      time: true,
    },
    {
      name: 'quantcase-bullboard',
      script: 'lib/admin.js',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '30s',
      restart_delay: 5000,
      out_file: 'logs/bullboard-out.log',
      error_file: 'logs/bullboard-error.log',
      time: true,
    },
    {
      name: 'quantcase-scheduler',
      script: 'scheduler.js',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '30s',
      restart_delay: 5000,
      out_file: 'logs/scheduler-out.log',
      error_file: 'logs/scheduler-error.log',
      time: true,
    },
  ],
};
