const FINCRUX_METRICS = [
  "ROE",
  "ROCE",
  "Stock P/E",
  "Book Value",
  "Face Value",
  "High / Low",
  "Market Cap",
  "Current Price",
  "Dividend Yield",
  "Sales",
  "Expenses",
  "Operating Profit",
  "OPM %",
  "Other Income",
  "Interest",
  "Depreciation",
  "Profit before tax",
  "Tax %",
  "Net Profit",
  "EPS in Rs",
  "Raw PDF",
  "Dividend Payout %",
  "Equity Capital",
  "Reserves",
  "Borrowings",
  "Other Liabilities",
  "Total Liabilities",
  "Fixed Assets",
  "CWIP",
  "Investments",
  "Other Assets",
  "Total Assets",
  "Cash from Operating Activity",
  "Cash from Investing Activity",
  "Cash from Financing Activity",
  "Net Cash Flow",
  "Debtor Days",
  "Inventory Days",
  "Days Payable",
  "Cash Conversion Cycle",
  "Working Capital Days",
  "Promoters",
  "Public",
  "No. of Shareholders"
];

module.exports = { FINCRUX_METRICS };